name: gestor-cursos-web-api
services:
  database:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword123
      POSTGRES_DB: gestorcursos
    ports:
      - "5432:5432"