// <auto-generated />
using System;
using GestorCursos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorCursos.Data.Migrations
{
    [DbContext(typeof(GestorCursosDbContext))]
    partial class GestorCursosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorCursos.Models.Estudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcc43a5f-c2a5-431d-9b5f-6d0791fdd3a0"),
                            DepartamentoId = new Guid("bfbd6728-01f4-48f7-850c-eca831b2fb32"),
                            Email = "juan.perez@example.com",
                            FechaNacimiento = new DateOnly(1990, 5, 15),
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = new Guid("1fd151d4-7623-4f7e-b4e9-c72bd313f5be"),
                            DepartamentoId = new Guid("d8bc6149-5282-4f49-87bb-7f02603721f8"),
                            Email = "maria.lopez@example.com",
                            FechaNacimiento = new DateOnly(1995, 8, 20),
                            Nombre = "María López"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
